#!/bin/bash
../azouk-libraries/build/mxcontrol run_multiplexer 127.0.0.1:1234 &

export PYTHONPATH=~/openbci/openbci/:~/azouk-libraries/build/

./openbci/ugm/run_ugm.py &

sleep 1

./openbci/main_gui.py &

#sleep 1

#./stop
