#!/bin/bash
./azouk-libraries/build/mxcontrol run_multiplexer 127.0.0.1:1234 &

export PYTHONPATH=openbci/:azouk-libraries/build/
#export PYTHONPATH=/home/pi/finals/final-1.1/openbci/:/home/pi/finals/final-1.1/azouk-libraries/build/
./openbci/hashtable.py &

sleep 1

./openbci/ugm.py &


