#!/bin/bash
./azouk-libraries/build/mxcontrol run_multiplexer 127.0.0.1:31889 &

export PYTHONPATH=./:openbci/:azouk-libraries/build/:PYTHONPATH

./openbci/hashtable.py &


./openbci/amplifiers/virtual_amplifier.py file &

sleep 1

./openbci/data_storage/signal_saver.py &

sleep 2

./openbci/data_storage/tests/test_manually_signal_saver_control.py start_saving &
