#!/bin/bash
azouk-libraries/build/mxcontrol run_multiplexer 127.0.0.1:31889 &

export PYTHONPATH=./:openbci/:azouk-libraries/build/:PYTHONPATH

python ./openbci/ugm/run_ugm.py &

sleep 1

python ./openbci/main_gui.py &

#sleep 1

#./stop
