#!/bin/bash
./azouk-libraries/build/mxcontrol run_multiplexer 127.0.0.1:31889 &
export PYTHONPATH=openbci/:azouk-libraries/build/

python ./openbci/tags/test_tags_receiving.py &

sleep 1

python ./openbci/tags/test_tags_sending.py &

