#!/bin/bash
./azouk-libraries/build/mxcontrol run_multiplexer 127.0.0.1:31889 &

export PYTHONPATH=openbci/:azouk-libraries/build/

./openbci/hashtable.py &

sleep 1

./openbci/signal_catcher.py &

sleep 1

./openbci/filters/filter.py &

sleep 1

./openbci/amplifiers/virtual_amplifier.py &

sleep 1

./openbci/ugm.py &

sleep 1

./openbci/logics/logic_speller.py &

sleep 1

./openbci/analysis/ssvep_analysis.py &


#sleep 1

#./stop
