#!/bin/bash
./azouk-libraries/build/mxcontrol run_multiplexer 127.0.0.1:1234 &
export PYTHONPATH=openbci/:azouk-libraries/build/

./openbci/hashtable.py &

sleep 1

./openbci/signal_catcher.py &

sleep 1

./openbci/filters/filter.py &

sleep 1

./openbci/amplifiers/virtual_amplifier.py file $1 $2 &

sleep 5

./openbci/monitors/monitor.py 0 &
./openbci/monitors/spectrum.py 0 &
