#!/bin/bash
./azouk-libraries/build/mxcontrol run_multiplexer 127.0.0.1:31889 &

sleep 2

export PYTHONPATH=./:openbci/:azouk-libraries/build/:PYTHONPATH

./openbci/hashtable.py &
sleep 1

./openbci/ugm/run_ugm.py &

sleep 2

./openbci/logics/logic_speller.py &

