#!/bin/bash
./azouk-libraries/build/mxcontrol run_multiplexer 127.0.0.1:31889 &

#rfcomm connect 0 &

export PYTHONPATH=openbci/:azouk-libraries/build/
#export PYTHONPATH=/home/pi/finals/final-1.1/openbci/:/home/pi/finals/final-1.1/azouk-libraries/build/
./openbci/hashtable.py &

sleep 1

./openbci/signal_catcher.py &

sleep 1

./openbci/filters/filter.py &

sleep 1

./openbci/amplifiers/virtual_amplifier.py &
#./openbci/amplifiers/tmsi_eeg_amplifier.py &

sleep 5

./openbci/monitors/monitor.py 0 &
./openbci/monitors/spectrum.py 0 &

