#!/bin/bash
./azouk-libraries/build/mxcontrol run_multiplexer 127.0.0.1:31889 &

rfcomm connect 0 &

sleep 2


export PYTHONPATH=./:openbci/:azouk-libraries/build/:PYTHONPATH

./openbci/hashtable.py &

sleep 1

./openbci/signal_catcher.py &

#sleep 1

#./openbci/filters/filter.py &

sleep 1

#./openbci/amplifiers/tmsi_bluetooth_eeg_amplifier.py 
./openbci/amplifiers/tmsi_eeg_amplifier.py &


sleep 4

./openbci/monitors/monitor.py 0 &

