#!/bin/bash
./azouk-libraries/build/mxcontrol run_multiplexer 127.0.0.1:31889 &

export PYTHONPATH=./:openbci/:azouk-libraries/build/:PYTHONPATH
./svarog/pinger.py &
./openbci/hashtable.py &
sleep 1
python ./openbci/amplifiers/virtual_amplifier.py file openbci/data_storage/tests/data/data.obci.info openbci/data_storage/tests/data/data.obci.dat  openbci/data_storage/tests/data/data.obci.tags &

sleep 3
./openbci/data_storage/signal_saver.py &
./openbci/data_storage/info_saver.py &
./openbci/tags/tag_saver.py &


