#!/bin/bash
./azouk-libraries/build/mxcontrol run_multiplexer 127.0.0.1:31889 &

#rfcomm connect 0 &

export PYTHONPATH=./:openbci/:azouk-libraries/build/:PYTHONPATH
#export PYTHONPATH=/home/pi/finals/final-1.1/openbci/:/home/pi/finals/final-1.1/azouk-libraries/build/

./openbci/hashtable.py &

#sleep 1

#./openbci/ugm.py &

sleep 1

./openbci/signal_catcher.py &

sleep 1 

./openbci/filters/filter.py &

sleep 1

./openbci/amplifiers/virtual_amplifier.py &

#./openbci/amplifiers/tmsi_eeg_amplifier.py &

sleep 4

./openbci/diode_catcher.py &

sleep 1

./openbci/super_diode_control_test.py &

sleep 1

./openbci/logics/logic_mixed.py &


sleep 4

./openbci/analysis/p300.py &

#sleep 1

#./openbci/analysis/ssvep_analysis.py &

#sleep 1

#./openbci/monitors/monitor.py 0 &

# sleep 1

# ./openbci/logics/logic_mixed.py &


