fields = [
    {
        'id':1,
        'width_type':'absolute',
        'width':350, 
        'height_type':'absolute',
        'height':350,
        'position_horizontal_type':'absolute',
        'position_horizontal':0,
        'position_vertical_type':'absolute',
        'position_vertical':0,
        'color':'#000000',
        'stimuluses':
            [
            {
                'id':11,
                'width_type':'relative',
                'width':1, 
                'height_type':'relative',
                'height':1, 
                'position_horizontal_type':'aligned',
                'position_horizontal':'center',
                'position_vertical_type':'aligned',
                'position_vertical':'center',
                'color':'#fffeee', 
                'stimulus_type':'diode',
                'freq':15.0,
                'stimuluses':[]
                }
            ]
        }, # End of 1 field definition
 {
        'id':2,
        'width_type':'absolute',
        'width':350, 
        'height_type':'absolute',
        'height':350,
        'position_horizontal_type':'absolute',
        'position_horizontal':350,
        'position_vertical_type':'absolute',
        'position_vertical':0,
        'color':'#d4d4d4',
        'stimuluses':
            [
            {
                'id':21,
                'width_type':'relative',
                'width':1, 
                'height_type':'relative',
                'height':1, 
                'position_horizontal_type':'aligned',
                'position_horizontal':'center',
                'position_vertical_type':'aligned',
                'position_vertical':'center',
                'color':'#fffeee', 
                'stimulus_type':'diode',
                'freq':15.0,
                'stimuluses':[]
                }
            ]
        }, # End of 2 field definition
 {
        'id':3,
        'width_type':'absolute',
        'width':350, 
        'height_type':'absolute',
        'height':350,
        'position_horizontal_type':'absolute',
        'position_horizontal':0,
        'position_vertical_type':'absolute',
        'position_vertical':350,
        'color':'#d4d4d4',
        'stimuluses':
            [
            {
                'id':31,
                'width_type':'relative',
                'width':1, 
                'height_type':'relative',
                'height':1, 
                'position_horizontal_type':'aligned',
                'position_horizontal':'center',
                'position_vertical_type':'aligned',
                'position_vertical':'center',
                'color':'#fffeee', 
                'stimulus_type':'diode',
                'freq':15.0,
                'stimuluses':[]
                }
            ]
        }, # End of 3 field definition
 {
        'id':4,
        'width_type':'absolute',
        'width':350, 
        'height_type':'absolute',
        'height':350,
        'position_horizontal_type':'absolute',
        'position_horizontal':350,
        'position_vertical_type':'absolute',
        'position_vertical':350,
        'color':'#d4d4d4',
        'stimuluses':
            [
            {
                'id':41,
                'width_type':'relative',
                'width':1, 
                'height_type':'relative',
                'height':1, 
                'position_horizontal_type':'aligned',
                'position_horizontal':'center',
                'position_vertical_type':'aligned',
                'position_vertical':'center',
                'color':'#fffeee', 
                'stimulus_type':'diode',
                'freq':15.0,
                'stimuluses':[]
                }
            ]
        }, # End of 4 field definition
{
        'id':5,
        'width_type':'absolute',
        'width':350, 
        'height_type':'absolute',
        'height':350,
        'position_horizontal_type':'absolute',
        'position_horizontal':800,
        'position_vertical_type':'aligned',
        'position_vertical':'center',
        'color':'#d4d4d4',
        'stimuluses':
            [
            {
                'id':51,
                'position_horizontal_type':'aligned',
                'position_horizontal':'center',
                'position_vertical_type':'aligned',
                'position_vertical':'center',
                'color':'#fffeee', 
                'stimulus_type':'image',
                'image_path':'juhu.png',
                'stimuluses':[]
                }
            ]
        } # End of 5 field definition
]
