# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_LAUNCHEDTASK_STATE = descriptor.EnumDescriptor(
  name='State',
  full_name='k2launcher.LaunchedTask.State',
  filename='State',
  values=[
    descriptor.EnumValueDescriptor(
      name='BORN', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RUNNING', index=1, number=1,
      options=None,
      type=None),
  ],
  options=None,
)

_COMMAND_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='k2launcher.Command.Type',
  filename='Type',
  values=[
    descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='KILL', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESTART', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STOP', index=3, number=3,
      options=None,
      type=None),
  ],
  options=None,
)

_SCHEDULERESPONSE_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='k2launcher.ScheduleResponse.Type',
  filename='Type',
  values=[
    descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ERROR_TASK_NOT_SPECIFIED', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ERROR_NOT_ENOUGH_ARGUMENTS', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ERROR_BAD_BABYSITTER', index=3, number=3,
      options=None,
      type=None),
  ],
  options=None,
)


_KEYVALUE = descriptor.Descriptor(
  name='KeyValue',
  full_name='k2launcher.KeyValue',
  filename='k2launcher.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='k2launcher.KeyValue.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='k2launcher.KeyValue.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TASK = descriptor.Descriptor(
  name='Task',
  full_name='k2launcher.Task',
  filename='k2launcher.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='k2launcher.Task.cmd', index=0,
      number=1, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='task_id', full_name='k2launcher.Task.task_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='node', full_name='k2launcher.Task.node', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("__ANY__", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='env', full_name='k2launcher.Task.env', index=3,
      number=4, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='screen_name', full_name='k2launcher.Task.screen_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='babysit_pidfile', full_name='k2launcher.Task.babysit_pidfile', index=5,
      number=6, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='babysit_screen', full_name='k2launcher.Task.babysit_screen', index=6,
      number=7, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pidfile', full_name='k2launcher.Task.pidfile', index=7,
      number=8, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='working_dir', full_name='k2launcher.Task.working_dir', index=8,
      number=9, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bash_debug', full_name='k2launcher.Task.bash_debug', index=9,
      number=10, type=8, cpp_type=7, label=1,
      default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bash_after', full_name='k2launcher.Task.bash_after', index=10,
      number=11, type=8, cpp_type=7, label=1,
      default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='date_at_the_beginning', full_name='k2launcher.Task.date_at_the_beginning', index=11,
      number=12, type=8, cpp_type=7, label=1,
      default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='babysit_delay', full_name='k2launcher.Task.babysit_delay', index=12,
      number=13, type=1, cpp_type=5, label=1,
      default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='expose_pidfile_in_env', full_name='k2launcher.Task.expose_pidfile_in_env', index=13,
      number=14, type=8, cpp_type=7, label=1,
      default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='generate_pidfile', full_name='k2launcher.Task.generate_pidfile', index=14,
      number=15, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_LAUNCHEDTASK = descriptor.Descriptor(
  name='LaunchedTask',
  full_name='k2launcher.LaunchedTask',
  filename='k2launcher.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='task', full_name='k2launcher.LaunchedTask.task', index=0,
      number=1, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='launched_node', full_name='k2launcher.LaunchedTask.launched_node', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='state', full_name='k2launcher.LaunchedTask.state', index=2,
      number=3, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='restart_counter', full_name='k2launcher.LaunchedTask.restart_counter', index=3,
      number=4, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _LAUNCHEDTASK_STATE,
  ],
  options=None)


_COMMAND = descriptor.Descriptor(
  name='Command',
  full_name='k2launcher.Command',
  filename='k2launcher.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='k2launcher.Command.id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='k2launcher.Command.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='task', full_name='k2launcher.Command.task', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='when', full_name='k2launcher.Command.when', index=3,
      number=4, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='priority', full_name='k2launcher.Command.priority', index=4,
      number=5, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _COMMAND_TYPE,
  ],
  options=None)


_SCHEDULERESPONSE = descriptor.Descriptor(
  name='ScheduleResponse',
  full_name='k2launcher.ScheduleResponse',
  filename='k2launcher.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='k2launcher.ScheduleResponse.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='k2launcher.ScheduleResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _SCHEDULERESPONSE_TYPE,
  ],
  options=None)


_GETNEXT = descriptor.Descriptor(
  name='GetNext',
  full_name='k2launcher.GetNext',
  filename='k2launcher.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='node', full_name='k2launcher.GetNext.node', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_GETTASKSTATE = descriptor.Descriptor(
  name='GetTaskState',
  full_name='k2launcher.GetTaskState',
  filename='k2launcher.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='task_id', full_name='k2launcher.GetTaskState.task_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TASK.fields_by_name['env'].message_type = _KEYVALUE
_LAUNCHEDTASK.fields_by_name['task'].message_type = _TASK
_LAUNCHEDTASK.fields_by_name['state'].enum_type = _LAUNCHEDTASK_STATE
_COMMAND.fields_by_name['type'].enum_type = _COMMAND_TYPE
_COMMAND.fields_by_name['task'].message_type = _TASK
_SCHEDULERESPONSE.fields_by_name['type'].enum_type = _SCHEDULERESPONSE_TYPE

class KeyValue(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _KEYVALUE

class Task(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASK

class LaunchedTask(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAUNCHEDTASK

class Command(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMAND

class ScheduleResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SCHEDULERESPONSE

class GetNext(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETNEXT

class GetTaskState(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETTASKSTATE

