# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='cfg_messages.proto',
  package='cfg_messages',
  serialized_pb='\n\x12\x63\x66g_messages.proto\x12\x0c\x63\x66g_messages\"$\n\x05Param\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"2\n\x0bParamVector\x12#\n\x06params\x18\x02 \x03(\x0b\x32\x13.cfg_messages.Param\"L\n\x13\x43onfigParamsRequest\x12\x0e\n\x06sender\x18\x01 \x02(\t\x12\x10\n\x08receiver\x18\x02 \x02(\t\x12\x13\n\x0bparam_names\x18\x03 \x03(\t\"[\n\x0c\x43onfigParams\x12\x0e\n\x06sender\x18\x01 \x02(\t\x12\x10\n\x08receiver\x18\x02 \x02(\t\x12)\n\x06params\x18\x03 \x02(\x0b\x32\x19.cfg_messages.ParamVector\" \n\x0ePeerReadyQuery\x12\x0e\n\x06sender\x18\x01 \x02(\t\"8\n\x0fPeerReadyStatus\x12\x10\n\x08receiver\x18\x01 \x02(\t\x12\x13\n\x0bpeers_ready\x18\x02 \x02(\x08')




_PARAM = descriptor.Descriptor(
  name='Param',
  full_name='cfg_messages.Param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='cfg_messages.Param.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='cfg_messages.Param.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=72,
)


_PARAMVECTOR = descriptor.Descriptor(
  name='ParamVector',
  full_name='cfg_messages.ParamVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='params', full_name='cfg_messages.ParamVector.params', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=74,
  serialized_end=124,
)


_CONFIGPARAMSREQUEST = descriptor.Descriptor(
  name='ConfigParamsRequest',
  full_name='cfg_messages.ConfigParamsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sender', full_name='cfg_messages.ConfigParamsRequest.sender', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='receiver', full_name='cfg_messages.ConfigParamsRequest.receiver', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='param_names', full_name='cfg_messages.ConfigParamsRequest.param_names', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=126,
  serialized_end=202,
)


_CONFIGPARAMS = descriptor.Descriptor(
  name='ConfigParams',
  full_name='cfg_messages.ConfigParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sender', full_name='cfg_messages.ConfigParams.sender', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='receiver', full_name='cfg_messages.ConfigParams.receiver', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='params', full_name='cfg_messages.ConfigParams.params', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=204,
  serialized_end=295,
)


_PEERREADYQUERY = descriptor.Descriptor(
  name='PeerReadyQuery',
  full_name='cfg_messages.PeerReadyQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sender', full_name='cfg_messages.PeerReadyQuery.sender', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=297,
  serialized_end=329,
)


_PEERREADYSTATUS = descriptor.Descriptor(
  name='PeerReadyStatus',
  full_name='cfg_messages.PeerReadyStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='receiver', full_name='cfg_messages.PeerReadyStatus.receiver', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='peers_ready', full_name='cfg_messages.PeerReadyStatus.peers_ready', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=331,
  serialized_end=387,
)

_PARAMVECTOR.fields_by_name['params'].message_type = _PARAM
_CONFIGPARAMS.fields_by_name['params'].message_type = _PARAMVECTOR
DESCRIPTOR.message_types_by_name['Param'] = _PARAM
DESCRIPTOR.message_types_by_name['ParamVector'] = _PARAMVECTOR
DESCRIPTOR.message_types_by_name['ConfigParamsRequest'] = _CONFIGPARAMSREQUEST
DESCRIPTOR.message_types_by_name['ConfigParams'] = _CONFIGPARAMS
DESCRIPTOR.message_types_by_name['PeerReadyQuery'] = _PEERREADYQUERY
DESCRIPTOR.message_types_by_name['PeerReadyStatus'] = _PEERREADYSTATUS

class Param(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARAM

  # @@protoc_insertion_point(class_scope:cfg_messages.Param)

class ParamVector(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARAMVECTOR

  # @@protoc_insertion_point(class_scope:cfg_messages.ParamVector)

class ConfigParamsRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONFIGPARAMSREQUEST

  # @@protoc_insertion_point(class_scope:cfg_messages.ConfigParamsRequest)

class ConfigParams(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONFIGPARAMS

  # @@protoc_insertion_point(class_scope:cfg_messages.ConfigParams)

class PeerReadyQuery(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PEERREADYQUERY

  # @@protoc_insertion_point(class_scope:cfg_messages.PeerReadyQuery)

class PeerReadyStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PEERREADYSTATUS

  # @@protoc_insertion_point(class_scope:cfg_messages.PeerReadyStatus)

# @@protoc_insertion_point(module_scope)
