#!/usr/bin/env bash

direc=$OBCI_INSTALL_DIR
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp

if [ -z $OBCI_INSTALL_DIR ]
then
	direc=$HOME/dev/openbci
fi
python $direc/obci_control/launcher/obci_script.py $@
