#!/bin/bash
export 
PYTHONPATH=../../:../../openbci/:../../azouk-libraries/build/:PYTHONPATH
python configure_amplifier.py $1 $2 $4
sleep 2
../../openbci/amplifiers/c_tmsi_amplifier/tmsi_server -d /dev/tmsi0