#!/bin/bash
echo 'use like: ./run_amplifier number_of_channels sampling duration values_type'
export PYTHONPATH=../../:../../openbci/:../../azouk-libraries/build/:PYTHONPATH
python configure_amplifier.py $1 $2 $4
sleep 2
../../openbci/amplifiers/c_tmsi_amplifier/test_server -s $2 -d $3