#!/usr/bin/env bash

direc=$OBCI_INSTALL_DIR
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
export DISPLAY=:0

if [ -z $OBCI_INSTALL_DIR ]
then
	direc=/usr/share/openbci
fi
exec python $direc/obci_control/gui/obci_x_tray.py
