# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'obci_launcher.ui'
#
# Created: Tue Feb 21 14:18:01 2012
#      by: pyside-uic 0.2.11 running on PySide 1.0.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ObciLauncher(object):
    def setupUi(self, ObciLauncher):
        ObciLauncher.setObjectName("ObciLauncher")
        ObciLauncher.resize(777, 452)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ObciLauncher.sizePolicy().hasHeightForWidth())
        ObciLauncher.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(ObciLauncher)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtGui.QSplitter(ObciLauncher)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtGui.QGroupBox(self.splitter)
        self.groupBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setBaseSize(QtCore.QSize(40, 0))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scenarios = QtGui.QTableWidget(self.groupBox)
        self.scenarios.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.scenarios.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.scenarios.setColumnCount(2)
        self.scenarios.setObjectName("scenarios")
        self.scenarios.setColumnCount(2)
        self.scenarios.setRowCount(0)
        self.scenarios.horizontalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.scenarios)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.info = QtGui.QLabel(self.groupBox_3)
        self.info.setWordWrap(True)
        self.info.setOpenExternalLinks(True)
        self.info.setObjectName("info")
        self.gridLayout_2.addWidget(self.info, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_button = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.stop_button = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout.addWidget(self.stop_button)
        self.reset_button = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_button.sizePolicy().hasHeightForWidth())
        self.reset_button.setSizePolicy(sizePolicy)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout.addWidget(self.reset_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.parameters_of = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameters_of.sizePolicy().hasHeightForWidth())
        self.parameters_of.setSizePolicy(sizePolicy)
        self.parameters_of.setMinimumSize(QtCore.QSize(0, 0))
        self.parameters_of.setObjectName("parameters_of")
        self.gridLayout_3 = QtGui.QGridLayout(self.parameters_of)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.parameters = QtGui.QTreeWidget(self.parameters_of)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameters.sizePolicy().hasHeightForWidth())
        self.parameters.setSizePolicy(sizePolicy)
        self.parameters.setMinimumSize(QtCore.QSize(390, 1))
        self.parameters.setObjectName("parameters")
        self.parameters.headerItem().setText(0, "1")
        self.gridLayout_3.addWidget(self.parameters, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.details_label = QtGui.QLabel(self.parameters_of)
        self.details_label.setObjectName("details_label")
        self.horizontalLayout_4.addWidget(self.details_label)
        self.details_mode = QtGui.QComboBox(self.parameters_of)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.details_mode.sizePolicy().hasHeightForWidth())
        self.details_mode.setSizePolicy(sizePolicy)
        self.details_mode.setObjectName("details_mode")
        self.horizontalLayout_4.addWidget(self.details_mode)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.splitter, 0, 1, 1, 1)

        self.retranslateUi(ObciLauncher)
        QtCore.QMetaObject.connectSlotsByName(ObciLauncher)

    def retranslateUi(self, ObciLauncher):
        ObciLauncher.setWindowTitle(QtGui.QApplication.translate("ObciLauncher", "OBCI Launcher", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ObciLauncher", "Experiment scenarios", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ObciLauncher", "Information", None, QtGui.QApplication.UnicodeUTF8))
        self.info.setText(QtGui.QApplication.translate("ObciLauncher", "asjdn asjklndjk naskljdh jkashdjk ashdkjhas kjashd akljshdk jlasd kjahdkjashd kjahsdjk hasdjlhasdklj hadkljashd lashd kjash djkashdkj ahsd lash", None, QtGui.QApplication.UnicodeUTF8))
        self.start_button.setText(QtGui.QApplication.translate("ObciLauncher", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_button.setText(QtGui.QApplication.translate("ObciLauncher", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_button.setText(QtGui.QApplication.translate("ObciLauncher", "Reset all", None, QtGui.QApplication.UnicodeUTF8))
        self.parameters_of.setTitle(QtGui.QApplication.translate("ObciLauncher", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.details_label.setText(QtGui.QApplication.translate("ObciLauncher", "Details mode:", None, QtGui.QApplication.UnicodeUTF8))

