#!/bin/bash


direc=$OBCI_INSTALL_DIR

if [ -z $OBCI_INSTALL_DIR ]
then
	direc=$HOME/dev/openbci
fi

export PYTHONPATH=`python $direc/obci_control/launcher/launcher_tools.py`
python $direc/obci_control/gui/obciLauncher.py $@