# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'obci_window.ui'
#
# Created: Fri Jul  6 17:15:06 2012
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_OBCILauncher(object):
    def setupUi(self, OBCILauncher):
        OBCILauncher.setObjectName("OBCILauncher")
        OBCILauncher.resize(873, 615)
        OBCILauncher.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        OBCILauncher.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(OBCILauncher)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtGui.QGroupBox(self.splitter)
        self.groupBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setBaseSize(QtCore.QSize(40, 0))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scenarios = QtGui.QTreeWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.scenarios.sizePolicy().hasHeightForWidth())
        self.scenarios.setSizePolicy(sizePolicy)
        self.scenarios.setObjectName("scenarios")
        self.scenarios.headerItem().setText(0, "1")
        self.verticalLayout_4.addWidget(self.scenarios)
        self.store_checkBox = QtGui.QCheckBox(self.groupBox)
        self.store_checkBox.setObjectName("store_checkBox")
        self.verticalLayout_4.addWidget(self.store_checkBox)
        self.store_container = QtGui.QWidget(self.groupBox)
        self.store_container.setObjectName("store_container")
        self.verticalLayout = QtGui.QVBoxLayout(self.store_container)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setSpacing(3)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtGui.QLabel(self.store_container)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.store_container)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.store_file = QtGui.QLineEdit(self.store_container)
        self.store_file.setObjectName("store_file")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.store_file)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.store_dir = QtGui.QLineEdit(self.store_container)
        self.store_dir.setObjectName("store_dir")
        self.horizontalLayout_7.addWidget(self.store_dir)
        self.store_dir_chooser = QtGui.QToolButton(self.store_container)
        self.store_dir_chooser.setObjectName("store_dir_chooser")
        self.horizontalLayout_7.addWidget(self.store_dir_chooser)
        self.formLayout_4.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.formLayout_4)
        self.store_ts_checkBox = QtGui.QCheckBox(self.store_container)
        self.store_ts_checkBox.setToolTip("")
        self.store_ts_checkBox.setStatusTip("")
        self.store_ts_checkBox.setWhatsThis("")
        self.store_ts_checkBox.setChecked(True)
        self.store_ts_checkBox.setObjectName("store_ts_checkBox")
        self.verticalLayout.addWidget(self.store_ts_checkBox)
        self.store_local_checkBox = QtGui.QCheckBox(self.store_container)
        self.store_local_checkBox.setEnabled(True)
        self.store_local_checkBox.setChecked(True)
        self.store_local_checkBox.setObjectName("store_local_checkBox")
        self.verticalLayout.addWidget(self.store_local_checkBox)
        self.verticalLayout_4.addWidget(self.store_container)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_button = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.stop_button = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout.addWidget(self.stop_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.parameters_of = QtGui.QGroupBox(self.splitter)
        self.parameters_of.setMinimumSize(QtCore.QSize(0, 0))
        self.parameters_of.setObjectName("parameters_of")
        self.gridLayout_3 = QtGui.QGridLayout(self.parameters_of)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.parameters = QtGui.QTreeWidget(self.parameters_of)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameters.sizePolicy().hasHeightForWidth())
        self.parameters.setSizePolicy(sizePolicy)
        self.parameters.setMinimumSize(QtCore.QSize(390, 1))
        self.parameters.setObjectName("parameters")
        self.parameters.headerItem().setText(0, "1")
        self.gridLayout_3.addWidget(self.parameters, 1, 0, 1, 1)
        self.info = QtGui.QLabel(self.parameters_of)
        self.info.setWordWrap(True)
        self.info.setOpenExternalLinks(True)
        self.info.setObjectName("info")
        self.gridLayout_3.addWidget(self.info, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.details_label = QtGui.QLabel(self.parameters_of)
        self.details_label.setObjectName("details_label")
        self.horizontalLayout_4.addWidget(self.details_label)
        self.details_mode = QtGui.QComboBox(self.parameters_of)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.details_mode.sizePolicy().hasHeightForWidth())
        self.details_mode.setSizePolicy(sizePolicy)
        self.details_mode.setObjectName("details_mode")
        self.horizontalLayout_4.addWidget(self.details_mode)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.splitter, 0, 0, 1, 1)
        OBCILauncher.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(OBCILauncher)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 23))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        OBCILauncher.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(OBCILauncher)
        self.statusbar.setObjectName("statusbar")
        OBCILauncher.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(OBCILauncher)
        self.toolBar.setObjectName("toolBar")
        OBCILauncher.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionSave_as = QtGui.QAction(OBCILauncher)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/filesaveas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_as.setIcon(icon)
        self.actionSave_as.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionSave_as.setIconVisibleInMenu(True)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionSave = QtGui.QAction(OBCILauncher)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/filesave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setMenuRole(QtGui.QAction.TextHeuristicRole)
        self.actionSave.setIconVisibleInMenu(True)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtGui.QAction(OBCILauncher)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/fileopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setIconVisibleInMenu(True)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAdd_to_sidebar = QtGui.QAction(OBCILauncher)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/stock_add-bookmark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_to_sidebar.setIcon(icon3)
        self.actionAdd_to_sidebar.setIconVisibleInMenu(True)
        self.actionAdd_to_sidebar.setObjectName("actionAdd_to_sidebar")
        self.actionExit = QtGui.QAction(OBCILauncher)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/stock_exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setIconVisibleInMenu(True)
        self.actionExit.setObjectName("actionExit")
        self.actionRemove_from_sidebar = QtGui.QAction(OBCILauncher)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/stock_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove_from_sidebar.setIcon(icon5)
        self.actionRemove_from_sidebar.setIconVisibleInMenu(True)
        self.actionRemove_from_sidebar.setObjectName("actionRemove_from_sidebar")
        self.actionConnect = QtGui.QAction(OBCILauncher)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect.setIcon(icon6)
        self.actionConnect.setObjectName("actionConnect")
        self.menubar.addAction(self.menuMenu.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave_as)
        self.toolBar.addAction(self.actionRemove_from_sidebar)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConnect)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()

        self.retranslateUi(OBCILauncher)
        QtCore.QMetaObject.connectSlotsByName(OBCILauncher)

    def retranslateUi(self, OBCILauncher):
        OBCILauncher.setWindowTitle(QtGui.QApplication.translate("OBCILauncher", "OBCI Launcher", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("OBCILauncher", "Experiment scenarios", None, QtGui.QApplication.UnicodeUTF8))
        self.store_checkBox.setText(QtGui.QApplication.translate("OBCILauncher", "store EEG signal and tags", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("OBCILauncher", "Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("OBCILauncher", "File name", None, QtGui.QApplication.UnicodeUTF8))
        self.store_file.setText(QtGui.QApplication.translate("OBCILauncher", "test1", None, QtGui.QApplication.UnicodeUTF8))
        self.store_dir.setText(QtGui.QApplication.translate("OBCILauncher", "~/", None, QtGui.QApplication.UnicodeUTF8))
        self.store_dir_chooser.setText(QtGui.QApplication.translate("OBCILauncher", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.store_ts_checkBox.setText(QtGui.QApplication.translate("OBCILauncher", "Append timestamp to file name", None, QtGui.QApplication.UnicodeUTF8))
        self.store_local_checkBox.setText(QtGui.QApplication.translate("OBCILauncher", "Store data locally", None, QtGui.QApplication.UnicodeUTF8))
        self.start_button.setText(QtGui.QApplication.translate("OBCILauncher", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_button.setText(QtGui.QApplication.translate("OBCILauncher", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.parameters_of.setTitle(QtGui.QApplication.translate("OBCILauncher", "Scenario data", None, QtGui.QApplication.UnicodeUTF8))
        self.info.setText(QtGui.QApplication.translate("OBCILauncher", "asjdn asjklndjk naskljdh jkashdjk ashdkjhas kjashd akljshdk jlasd kjahdkjashd kjahsdjk hasdjlhasdklj hadkljashd lashd kjash djkashdkj ahsd lash", None, QtGui.QApplication.UnicodeUTF8))
        self.details_label.setText(QtGui.QApplication.translate("OBCILauncher", "Details mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("OBCILauncher", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("OBCILauncher", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setText(QtGui.QApplication.translate("OBCILauncher", "Save as...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setShortcut(QtGui.QApplication.translate("OBCILauncher", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("OBCILauncher", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("OBCILauncher", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("OBCILauncher", "Import...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("OBCILauncher", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_to_sidebar.setText(QtGui.QApplication.translate("OBCILauncher", "Add to sidebar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_to_sidebar.setShortcut(QtGui.QApplication.translate("OBCILauncher", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("OBCILauncher", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("OBCILauncher", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_from_sidebar.setText(QtGui.QApplication.translate("OBCILauncher", "Remove from sidebar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_from_sidebar.setShortcut(QtGui.QApplication.translate("OBCILauncher", "Ctrl+Shift+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setText(QtGui.QApplication.translate("OBCILauncher", "Connect...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setToolTip(QtGui.QApplication.translate("OBCILauncher", "Connect to another machine", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setShortcut(QtGui.QApplication.translate("OBCILauncher", "Ctrl+Shift+C", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
