# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UGMArea.ui'
#
# Created: Fri Jan 15 14:06:14 2010
#      by: PyQt4 UI code generator 4.6.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_UGMAreaWidget(object):
    def setupUi(self, UGMAreaWidget):
        UGMAreaWidget.setObjectName("UGMAreaWidget")
        UGMAreaWidget.resize(279, 349)
        self.formLayout = QtGui.QFormLayout(UGMAreaWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName("formLayout")
        self.IDLabel = QtGui.QLabel(UGMAreaWidget)
        self.IDLabel.setObjectName("IDLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.IDLabel)
        self.IDLineEdit = QtGui.QLineEdit(UGMAreaWidget)
        self.IDLineEdit.setObjectName("IDLineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.IDLineEdit)
        self.parameterLabel = QtGui.QLabel(UGMAreaWidget)
        self.parameterLabel.setObjectName("parameterLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.parameterLabel)
        self.parameterSpinBox = QtGui.QSpinBox(UGMAreaWidget)
        self.parameterSpinBox.setObjectName("parameterSpinBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.parameterSpinBox)
        self.parameter2CheckBox = QtGui.QCheckBox(UGMAreaWidget)
        self.parameter2CheckBox.setChecked(False)
        self.parameter2CheckBox.setObjectName("parameter2CheckBox")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.parameter2CheckBox)
        self.groupBox = QtGui.QGroupBox(UGMAreaWidget)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setMargin(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stimulusToolbarFrame = QtGui.QFrame(self.groupBox)
        self.stimulusToolbarFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.stimulusToolbarFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.stimulusToolbarFrame.setObjectName("stimulusToolbarFrame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.stimulusToolbarFrame)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stimulusComboBox = QtGui.QComboBox(self.stimulusToolbarFrame)
        self.stimulusComboBox.setObjectName("stimulusComboBox")
        self.horizontalLayout.addWidget(self.stimulusComboBox)
        self.addStimulusButton = QtGui.QToolButton(self.stimulusToolbarFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addStimulusButton.sizePolicy().hasHeightForWidth())
        self.addStimulusButton.setSizePolicy(sizePolicy)
        self.addStimulusButton.setMaximumSize(QtCore.QSize(18, 18))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/buttons/add"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.addStimulusButton.setIcon(icon)
        self.addStimulusButton.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.addStimulusButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.addStimulusButton.setAutoRaise(False)
        self.addStimulusButton.setArrowType(QtCore.Qt.NoArrow)
        self.addStimulusButton.setObjectName("addStimulusButton")
        self.horizontalLayout.addWidget(self.addStimulusButton)
        self.removeStimulusButton = QtGui.QToolButton(self.stimulusToolbarFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeStimulusButton.sizePolicy().hasHeightForWidth())
        self.removeStimulusButton.setSizePolicy(sizePolicy)
        self.removeStimulusButton.setMaximumSize(QtCore.QSize(18, 18))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttons/remove"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.removeStimulusButton.setIcon(icon1)
        self.removeStimulusButton.setAutoRaise(False)
        self.removeStimulusButton.setArrowType(QtCore.Qt.NoArrow)
        self.removeStimulusButton.setObjectName("removeStimulusButton")
        self.horizontalLayout.addWidget(self.removeStimulusButton)
        self.verticalLayout.addWidget(self.stimulusToolbarFrame)
        self.stimulusInfoFrame = QtGui.QFrame(self.groupBox)
        self.stimulusInfoFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.stimulusInfoFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.stimulusInfoFrame.setObjectName("stimulusInfoFrame")
        self.verticalLayout.addWidget(self.stimulusInfoFrame)
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.groupBox)

        self.retranslateUi(UGMAreaWidget)
        QtCore.QMetaObject.connectSlotsByName(UGMAreaWidget)

    def retranslateUi(self, UGMAreaWidget):
        UGMAreaWidget.setWindowTitle(QtGui.QApplication.translate("UGMAreaWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.IDLabel.setText(QtGui.QApplication.translate("UGMAreaWidget", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.parameterLabel.setText(QtGui.QApplication.translate("UGMAreaWidget", "Kolejność", None, QtGui.QApplication.UnicodeUTF8))
        self.parameter2CheckBox.setText(QtGui.QApplication.translate("UGMAreaWidget", "ŻE CO?", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("UGMAreaWidget", "Bodźce", None, QtGui.QApplication.UnicodeUTF8))
        self.addStimulusButton.setText(QtGui.QApplication.translate("UGMAreaWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.removeStimulusButton.setText(QtGui.QApplication.translate("UGMAreaWidget", "...", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
