# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UGMMain.ui'
#
# Created: Tue Jan 19 18:24:35 2010
#      by: PyQt4 UI code generator 4.6.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_UGMMainWidget(object):
    def setupUi(self, UGMMainWidget):
        UGMMainWidget.setObjectName("UGMMainWidget")
        UGMMainWidget.resize(365, 445)
        UGMMainWidget.setMinimumSize(QtCore.QSize(358, 208))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.mainVLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.mainVLayout.setSpacing(0)
        self.mainVLayout.setMargin(2)
        self.mainVLayout.setObjectName("mainVLayout")
        self.toolbarFrame = QtGui.QFrame(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbarFrame.sizePolicy().hasHeightForWidth())
        self.toolbarFrame.setSizePolicy(sizePolicy)
        self.toolbarFrame.setMaximumSize(QtCore.QSize(16777215, 22))
        self.toolbarFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolbarFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.toolbarFrame.setLineWidth(1)
        self.toolbarFrame.setObjectName("toolbarFrame")
        self.toolbarHLayout = QtGui.QHBoxLayout(self.toolbarFrame)
        self.toolbarHLayout.setSpacing(2)
        self.toolbarHLayout.setMargin(2)
        self.toolbarHLayout.setObjectName("toolbarHLayout")
        self.addButton = QtGui.QToolButton(self.toolbarFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setMaximumSize(QtCore.QSize(18, 18))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/buttons/add"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.addButton.setIcon(icon)
        self.addButton.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.addButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.addButton.setAutoRaise(False)
        self.addButton.setArrowType(QtCore.Qt.NoArrow)
        self.addButton.setObjectName("addButton")
        self.toolbarHLayout.addWidget(self.addButton)
        self.removeButton = QtGui.QToolButton(self.toolbarFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeButton.sizePolicy().hasHeightForWidth())
        self.removeButton.setSizePolicy(sizePolicy)
        self.removeButton.setMaximumSize(QtCore.QSize(18, 18))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttons/remove"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.removeButton.setIcon(icon1)
        self.removeButton.setAutoRaise(False)
        self.removeButton.setArrowType(QtCore.Qt.NoArrow)
        self.removeButton.setObjectName("removeButton")
        self.toolbarHLayout.addWidget(self.removeButton)
        self.frame = QtGui.QFrame(self.toolbarFrame)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 1))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.toolbarHLayout.addWidget(self.frame)
        self.mainVLayout.addWidget(self.toolbarFrame)
        self.areasFrame = QtGui.QFrame(self.dockWidgetContents)
        self.areasFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.areasFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.areasFrame.setLineWidth(0)
        self.areasFrame.setObjectName("areasFrame")
        self.areasVLayout = QtGui.QVBoxLayout(self.areasFrame)
        self.areasVLayout.setSpacing(2)
        self.areasVLayout.setMargin(2)
        self.areasVLayout.setObjectName("areasVLayout")
        self.propertyList = QtGui.QTreeView(self.areasFrame)
        self.propertyList.setMinimumSize(QtCore.QSize(350, 0))
        self.propertyList.setAlternatingRowColors(True)
        self.propertyList.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.propertyList.setIndentation(12)
        self.propertyList.setRootIsDecorated(True)
        self.propertyList.setUniformRowHeights(True)
        self.propertyList.setAnimated(True)
        self.propertyList.setAllColumnsShowFocus(True)
        self.propertyList.setHeaderHidden(True)
        self.propertyList.setObjectName("propertyList")
        self.propertyList.header().setVisible(False)
        self.areasVLayout.addWidget(self.propertyList)
        self.mainVLayout.addWidget(self.areasFrame)
        UGMMainWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(UGMMainWidget)
        QtCore.QMetaObject.connectSlotsByName(UGMMainWidget)
        UGMMainWidget.setTabOrder(self.propertyList, self.addButton)
        UGMMainWidget.setTabOrder(self.addButton, self.removeButton)

    def retranslateUi(self, UGMMainWidget):
        UGMMainWidget.setWindowTitle(QtGui.QApplication.translate("UGMMainWidget", "DockWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("UGMMainWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setText(QtGui.QApplication.translate("UGMMainWidget", "...", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
