#!/bin/bash
cd ../../../
./azouk-libraries/build/mxcontrol run_multiplexer 127.0.0.1:31889 &

export PYTHONPATH=./:openbci/:azouk-libraries/build/:PYTHONPATH
./svarog/pinger.py &
./openbci/hashtable.py &

sleep 2
time ./openbci/amplifiers/c_tmsi_amplifier/tmsiAmpServer -l 128 &

