#!/bin/bash
cd ../../../
./azouk-libraries/build/mxcontrol run_multiplexer 0.0.0.0:31889 &

export PYTHONPATH=./:openbci/:azouk-libraries/build/:PYTHONPATH
./openbci/hashtable.py &

sleep 2
#./openbci/filters/autoscale_generator.py &
#./openbci/signal_streamer.py &
#./openbci/signal_catcher.py &
#./svarog/pinger.py &
./openbci/amplifiers/c_tmsi_amplifier/dummyReceiver -l 1024 &
time ./openbci/amplifiers/c_tmsi_amplifier/tmsiAmpServer  &

