#!/bin/bash
cd ../../../
./azouk-libraries/build/mxcontrol run_multiplexer 0.0.0.0:31889 &

export PYTHONPATH=./:openbci/:azouk-libraries/build/:PYTHONPATH
./openbci/hashtable.py &

sleep 2
./openbci/amplifiers/c_tmsi_amplifier/dummy_receiver -l 1024 &
time ./openbci/amplifiers/c_tmsi_amplifier/tmsi_server  &

