#!/bin/bash

type=$2
echo ""

if [ -z "$1" ]; then
    echo "Usage: obci_local_copy relative_directory_name"
    exit 1
fi

if [ -z "$2" ]; then
    type="local"
fi

pwd=`pwd`
OBCI_INSTALL_DIR=$(cd $pwd/$1 && pwd)

echo "OBCI_INSTALL_DIR is detected as $OBCI_INSTALL_DIR"
echo ""

if [ -d $OBCI_INSTALL_DIR ]; then
    echo "Directory '$OBCI_INSTALL_DIR' exists, not copying OpenBCI source!"
    echo "It's OK if you already have OpenBCI source in that directory."
    echo "If you don't, delete it first and run command again!"
    echo ""
else
    if [ $type == "local" ]; then
	    echo "Cloning branch master from git repository to '$OBCI_INSTALL_DIR'"
	    git clone https://github.com/BrainTech/openbci.git $OBCI_INSTALL_DIR
        
        if dpkg -s "openbci-multiplexer" 2>/dev/null 1>/dev/null
        then
	        mkdir -p $OBCI_INSTALL_DIR/multiplexer-install/bin/
	        ln -s /usr/bin/mxcontrol $OBCI_INSTALL_DIR/multiplexer-install/bin/mxcontrol
	    else
	        sudo apt-get update && sudo apt-get install git-core g++ python-dev maven2 openjdk-6-jdk patch libboost-all-dev libbluetooth-dev fxload xsel python-dev python-serial python-pygame python-scipy python-numpy python-sip python-qt4 python-bluetooth gnulib python-xlib screen libzmq-dev python-zmq unzip python-pyaudio
	     
	        cd $OBCI_INSTALL_DIR/scripts
	        ./install_mx.sh
	    fi

	    if dpkg -s "openbci-amplifiers" 2>/dev/null 1>/dev/null
	    then
	        ln -s /usr/bin/tmsi_amplifier $OBCI_INSTALL_DIR/drivers/eeg/cpp_amplifiers/tmsi_amplifier
	        ln -s /usr/bin/dummy_amplifier $OBCI_INSTALL_DIR/drivers/eeg/cpp_amplifiers/dummy_amplifier
	        ln -s /usr/bin/file_amplifier $OBCI_INSTALL_DIR/drivers/eeg/cpp_amplifiers/file_amplifier
        else
	        echo "Cloning azouk-libraries form git repository"
	        git clone https://github.com/BrainTech/azouk-libraries.git
	        sudo apt-get update && sudo apt-get install git-core g++ python-dev maven2 openjdk-6-jdk patch libboost-all-dev libbluetooth-dev fxload xsel python-dev python-serial python-pygame python-scipy python-numpy python-sip python-qt4 python-bluetooth gnulib python-xlib screen libzmq-dev python-zmq unzip python-pyaudio
	        cd $OBCI_INSTALL_DIR/scripts
	        ./install_drivers.sh
        fi
    elif [ $type == "compile" ]; then
	    sudo apt-get update && sudo apt-get install git-core g++ python-dev maven2 openjdk-6-jdk patch libboost-all-dev libbluetooth-dev fxload xsel python-dev python-serial python-pygame python-scipy python-numpy python-sip python-qt4 python-bluetooth gnulib python-xlib screen libzmq-dev python-zmq unzip python-pyaudio

	    echo "Cloning openBCI source form git repository..."
	    git clone https://github.com/BrainTech/openbci.git $OBCI_INSTALL_DIR
	    echo "Cloning azouk-libraries form git repository"
	    git clone https://github.com/BrainTech/azouk-libraries.git
	    cd $OBCI_INSTALL_DIR/scripts
	    echo "Installing local copy of multiplexer and drivers..."
	    ./install_mx.sh
	    ./install_drivers.sh
	    #./install_mx_and_drivers.sh
    else
	    echo "Usage: obci_local_copy directory_name [compile]"
	    exit 1
    fi
fi

HOME_DIR=$(cd ~ && pwd)

mkdir -p ~/.local/lib/python2.7/site-packages/
ln -s $OBCI_INSTALL_DIR ~/.local/lib/python2.7/site-packages/obci

rm -rf ~/.local/lib/python2.7/site-packages/multiplexer
rm -rf ~/.local/lib/python2.7/site-packages/azouk
rm -rf ~/.local/lib/python2.7/site-packages/azlib
rm -rf ~/.local/lib/python2.7/site-packages/obci
sed -i '/OBCI_INSTALL_DIR/d' ~/.bashrc
sed -i '/OBCI_INSTALL_DIR/d' ~/.profile
sed -i '/OBCI_PYTHONPATH/d' ~/.bashrc
sed -i '/OBCI_PYTHONPATH/d' ~/.profile
echo 'export OBCI_INSTALL_DIR='$OBCI_INSTALL_DIR >> ~/.profile
echo 'export OBCI_INSTALL_DIR='$OBCI_INSTALL_DIR >> ~/.bashrc
echo 'export PYTHONPATH='$HOME_DIR/.local/lib/python2.7/site-packages:\${PYTHONPATH} \# OBCI_PYTHONPATH >> ~/.profile
echo 'export PYTHONPATH='$HOME_DIR/.local/lib/python2.7/site-packages:\${PYTHONPATH} \# OBCI_PYTHONPATH>> ~/.bashrc

echo "Generating scripts..."
mkdir -p ~/bin
rm -rf ~/bin/obci
rm -rf ~/bin/obci_gui
rm -rf ~/bin/obci_local_copy
rm -rf ~/bin/obci_local_remove

if [ $type == "compile" ]
then
    ln -s $OBCI_INSTALL_DIR/multiplexer-install/lib/python2.7/site-packages/multiplexer ~/.local/lib/python2.7/site-packages/multiplexer
    ln -s $OBCI_INSTALL_DIR/multiplexer-install/lib/python2.7/site-packages/azouk ~/.local/lib/python2.7/site-packages/azouk
    ln -s $OBCI_INSTALL_DIR/multiplexer-install/lib/python2.7/site-packages/azlib ~/.local/lib/python2.7/site-packages/azlib
fi

ln -s $OBCI_INSTALL_DIR/control/launcher/obci ~/bin/obci
ln -s $OBCI_INSTALL_DIR/control/gui/obci_gui ~/bin/obci_gui
ln -s $OBCI_INSTALL_DIR/scripts/obci_local_copy ~/bin/obci_local_copy
ln -s $OBCI_INSTALL_DIR/scripts/obci_local_remove ~/bin/obci_local_remove

echo ""
echo "Operation complete, remember to restart your X session!"
echo ""
echo "You can reverse system changes by launchng obci_local_remove script."
echo "It won't remove '$OBCI_INSTALL_DIR' directory, you have to remove it yourself if you want."
echo ""

