#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: obci_local_activate relative_directory_name"
    exit 1
fi

if [ ! -d $1 ]; then
    echo "Error: Directory '$1' doesn't exist."
    exit 1
fi

PWD=`pwd`
OBCI_LOCAL_DIR=$(cd $PWD/$1 && pwd)

echo ""
echo "OBCI_LOCAL_DIR is detected as '$OBCI_LOCAL_DIR'"
echo ""

mkdir -p ~/.obci
echo "$OBCI_LOCAL_DIR" > ~/.obci/local_path

echo "Install local OpenBCI executables (if unsure choose n)? [y/n] "
read answer
if [[ ${answer} = "Y" || ${answer} = "y" ]]; then
    HOME_DIR=$(cd ~ && pwd)
    sed -i '/OPENBCI_PATH/d' ~/.bashrc
    sed -i '/OPENBCI_PATH/d' ~/.profile
    echo 'export PATH='$HOME_DIR/bin:\${PATH} \# OPENBCI_PATH >> ~/.profile
    echo 'export PATH='$HOME_DIR/bin:\${PATH} \# OPENBCI_PATH >> ~/.bashrc

    echo "Creating symlinks..."

    mkdir -p ~/bin

    rm -rf ~/bin/obci
    rm -rf ~/bin/obci_server
    rm -rf ~/bin/obci_gui
    rm -rf ~/bin/obci_tray

    rm -rf ~/bin/obci_local_copy
    rm -rf ~/bin/obci_local_remove

    ln -s $OBCI_LOCAL_DIR/bin/obci ~/bin/obci
    ln -s $OBCI_LOCAL_DIR/bin/obci_server ~/bin/obci_server
    ln -s $OBCI_LOCAL_DIR/bin/obci_gui ~/bin/obci_gui
    ln -s $OBCI_LOCAL_DIR/bin/obci_tray ~/bin/obci_tray

    ln -s $OBCI_LOCAL_DIR/scripts/obci_local_activate ~/bin/obci_local_activate
    ln -s $OBCI_LOCAL_DIR/scripts/obci_local_remove ~/bin/obci_local_remove

    echo "Operation completed. System restart or logging out IS REQUIRED."
else
    echo "Operation completed. System restart or logging out is not required."
fi

echo ""
echo "OpenBCI is now configured to run from '$OBCI_LOCAL_DIR'"
echo "You can reverse system changes by launchng 'obci_local_remove' script."

