#!/bin/bash
type=$2
echo ""
if [ -z "$1" ]
then
        echo "Usage: obci_local_copy relative_directory_name [(local) | master]"
	exit 1
fi
if [ -z "$2" ]
then
       type="local"
fi


pwd=`pwd`
if [ -d $pwd/$1 ]
then
       echo "Directory "$1" exists, not copying OpenBCI source!
It's OK if you already have OpenBCI source in that directory.
If you don't, delete it first and run command again!"

else
    if [ $type == "local" ]
    then
	echo 'Cloning branch master from git repository to '$pwd/$1
	git clone git://git.braintech.pl/openbci.git $pwd/$1
         if dpkg -s "openbci-multiplexer" 2>/dev/null 1>/dev/null
         then
	     mkdir -p $pwd/$1/multiplexer-install/bin/
	     ln -s /usr/bin/mxcontrol $pwd/$1/multiplexer-install/bin/mxcontrol
	 else
	     sudo apt-get update && sudo apt-get install git-core g++ python-dev maven2 openjdk-6-jdk patch libboost-all-dev libbluetooth-dev fxload xsel python-dev python-serial python-pygame python-scipy python-numpy python-sip python-qt4 python-bluetooth gnulib python-xlib screen libzmq-dev python-zmq unzip python-pyaudio
	     
	     cd $pwd/$1/scripts
	     ./install_mx.sh
	 fi

	 if dpkg -s "openbci-amplifiers" 2>/dev/null 1>/dev/null
	 then
	     ln -s /usr/bin/tmsi_amplifier $pwd/$1/drivers/eeg/cpp_amplifiers/tmsi_amplifier
	     ln -s /usr/bin/dummy_amplifier $pwd/$1/drivers/eeg/cpp_amplifiers/dummy_amplifier
	     ln -s /usr/bin/file_amplifier $pwd/$1/drivers/eeg/cpp_amplifiers/file_amplifier
         else
	     echo 'Cloning azouk-libraries form git repository'
	     git clone git://git.braintech.pl/azouk-libraries.git
	     sudo apt-get update && sudo apt-get install git-core g++ python-dev maven2 openjdk-6-jdk patch libboost-all-dev libbluetooth-dev fxload xsel python-dev python-serial python-pygame python-scipy python-numpy python-sip python-qt4 python-bluetooth gnulib python-xlib screen libzmq-dev python-zmq unzip python-pyaudio
	     cd $pwd/$1/scripts
	     ./install_drivers.sh
         fi

   elif [ $type == "compile" ]
   then
	sudo apt-get update && sudo apt-get install git-core g++ python-dev maven2 openjdk-6-jdk patch libboost-all-dev libbluetooth-dev fxload xsel python-dev python-serial python-pygame python-scipy python-numpy python-sip python-qt4 python-bluetooth gnulib python-xlib screen libzmq-dev python-zmq unzip python-pyaudio

	echo 'Cloning openBCI source form git repository...'
	git clone git://git.braintech.pl/openbci.git $pwd/$1
	echo 'Cloning azouk-libraries form git repository'
	git clone git://git.braintech.pl/azouk-libraries.git
	cd $pwd/$1/scripts
	echo 'Installing local copy of multiplexer and drivers...'
	./install_mx.sh
	./install_drivers.sh
	#./install_mx_and_drivers.sh
   else
	echo "Usage: obci_local_copy directory_name [compile]"
	exit 1
  fi
fi

rm -rf ~/.local/lib/python2.7/site-packages/multiplexer
rm -rf ~/.local/lib/python2.7/site-packages/azouk
rm -rf ~/.local/lib/python2.7/site-packages/azlib
rm -rf ~/.local/lib/python2.7/site-packages/obci
sed -i '/OBCI_INSTALL_DIR/d' ~/.bashrc
sed -i '/OBCI_INSTALL_DIR/d' ~/.profile
echo 'export OBCI_INSTALL_DIR='$pwd/$1 >> ~/.profile
echo 'export OBCI_INSTALL_DIR='$pwd/$1 >> ~/.bashrc
mkdir -p ~/.local/lib/python2.7/site-packages/
ln -s $pwd/$1 ~/.local/lib/python2.7/site-packages/obci

echo 'Generating scripts...'
mkdir -p ~/bin
rm -rf ~/bin/obci
rm -rf ~/bin/obci_gui
rm -rf ~/bin/obci_local_copy
rm -rf ~/bin/obci_local_remove

if [ $type == "compile" ]
then
ln -s $pwd/$1/multiplexer-install/lib/python2.7/site-packages/multiplexer ~/.local/lib/python2.7/site-packages/multiplexer
ln -s $pwd/$1/multiplexer-install/lib/python2.7/site-packages/azouk ~/.local/lib/python2.7/site-packages/azouk
ln -s $pwd/$1/multiplexer-install/lib/python2.7/site-packages/azlib ~/.local/lib/python2.7/site-packages/azlib
fi


ln -s $pwd/$1/control/launcher/obci ~/bin/obci
ln -s $pwd/$1/control/gui/obci_gui ~/bin/obci_gui
ln -s $pwd/$1/scripts/obci_local_copy ~/bin/obci_local_copy
ln -s $pwd/$1/scripts/obci_local_remove ~/bin/obci_local_remove

echo ''
echo 'Operation complete, remember to restart your X session!'
echo ''
echo 'You can reverse system changes by launchng obci_local_remove script.
It wont remove '$1' directory, you have to remove it yourself if you want.'
echo ''
