#!/bin/bash

echo ""

rm -rf ~/bin/obci
rm -rf ~/bin/obci_server
rm -rf ~/bin/obci_gui
rm -rf ~/bin/obci_tray

rm -rf ~/bin/obci_local_copy
rm -rf ~/bin/obci_local_remove

sed -i '/OPENBCI_PATH/d' ~/.bashrc
sed -i '/OPENBCI_PATH/d' ~/.profile

rm -rf ~/.obci/local_path

echo "Operation completed. Remember to restart your system or logout!"
echo ""

