#!/usr/bin/env bash

direc=$OBCI_INSTALL_DIR


if [ `uname` == Linux* ]
then
    export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
fi
export DISPLAY=:0

if [ -z "$OBCI_INSTALL_DIR" ]
then
	direc=/usr/share/openbci
fi
exec python "$direc/control/launcher/obci_script.py" $@
