#!/usr/bin/env bash

direc=$OBCI_INSTALL_DIR



if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
    if [ -z "$DISPLAY" ]
    then
	export DISPLAY=:0
    fi
fi

if [ -z "$OBCI_INSTALL_DIR" ]
then
	direc=/usr/share/openbci
fi
exec python "$direc/control/launcher/obci_script.py" $@
